export const APPLICATION_EVENTS_MESSAGES_SYSTEM = [
  'GENERAL_ERROR',
  'SUCCESS',
  'NOT_FOUND'
] as const


export const APPLICATION_EVENTS_MESSAGES = [
  ...APPLICATION_EVENTS_MESSAGES_SYSTEM,

  'USER_LOGGED_IN',
  'CANNOT_LOGIN',
  'ALREADY_LOGGED',
  'UNAUTHORIZED',

  'USER_CREATED',
  'CANNOT_CREATE_USER',

  'USER_DELETED',
  'SELF_USER_DELETED',
  'CANNOT_DELETE_USER'

] as const
export type APPLICATION_EVENTS_MESSAGES_TYPE = typeof APPLICATION_EVENTS_MESSAGES[number]

export const APPLICATION_EVENTS_COMMANDS = [
  'USER_LOGIN',
  'USER_LOGOUT',
  'USER_CREATE',
  'USER_GET_CURRENT',
  'USER_DELETE_ANY',
  'USER_DELETE_ACCOUNT_SCOPE_ONLY',
  'USER_DELETE_SELF_ONLY',
  'USER_GET_ALL'
] as const
export type APPLICATION_EVENTS_COMMANDS_TYPE = typeof APPLICATION_EVENTS_COMMANDS[number]

export const APPLICATION_EVENTS_ALL = [
  ...APPLICATION_EVENTS_MESSAGES,
  ...APPLICATION_EVENTS_COMMANDS
] as const

export type APPLICATION_EVENTS_ALL_TYPE = typeof APPLICATION_EVENTS_ALL[number]
