export const EVENT_LOGS_APPLICATION = [
  'GENERAL_ERROR',
  'SUCCESS',
  'NOT_FOUND'
] as const


export const EVENT_LOGS = [
  ...EVENT_LOGS_APPLICATION,

  'USER_LOGGED_IN',
  'CANNOT_LOGIN',
  'ALREADY_LOGGED',
  'UNAUTHORIZED',

  'USER_CREATED',
  'CANNOT_CREATE_USER',

  'USER_DELETED',
  'SELF_USER_DELETED',
  'CANNOT_DELETE_USER',

  'SESSION_DELETED',
  'CANNOT_DELETE_SESSION',
  'ALL_SESSIONS_DELETED',
  'CANNOT_DELETE_SESSIONS',

  'ACCOUNT_CREATED',
  'CANNOT_CREATE_ACCOUNT',
  'ACCOUNT_NOT_PAID'

] as const
export type EVENT_LOGS_TYPE = typeof EVENT_LOGS[number]

export const EVENT_COMMANDS = [
  'EVENT_LOG_GET_ALL',

  'USER_LOGIN',
  'USER_LOGOUT',
  'USER_CREATE',
  'USER_GET_CURRENT',
  'USER_DELETE_ANY',
  'USER_DELETE_ACCOUNT_SCOPE_ONLY',
  'USER_DELETE_SELF_ONLY',
  'USER_GET_ALL',

  'SESSION_DELETE_SELF_ONLY',
  'SESSION_DELETE_ALL',
  'SESSION_DELETE_SPECIFIC',
  'SESSION_GET_ALL',

  'ACCOUNT_CREATE'


] as const
export type EVENT_COMMANDS_TYPE = typeof EVENT_COMMANDS[number]

export const EVENT_LOGS_AND_COMMANDS = [
  ...EVENT_LOGS,
  ...EVENT_COMMANDS
] as const

export type EVENT_LOGS_AND_COMMANDS_TYPE = typeof EVENT_LOGS_AND_COMMANDS[number]
